### ISSUE TITLE
How to configure "me / my" for owner?

### ISSUE THREAD

**Issue by dpalic** [znuny/Znuny-DashboardWidgetSearchProfile#1]
Is there a way to configure "me" for owner queries?

e.g. to define a profile

shared-my-escalated-tickets

it shall always display only the current logged in userId as owner

**Comment by hanneshal** [comment]
Hi,

this is not possible / implemented yet. We use the default ticket search attributes as source for the widgets.
As long as they don't have such element, this add-on can not use it. 

regards

**Comment by dpalic** [comment]
> Hi,
> 
> this is not possible / implemented yet. We use the default ticket search attributes as source for the widgets. As long as they don't have such element, this add-on can not use it.
> 
> regards

Understand it is not done now, but to share such feature in a team, it shall be possible to map queries to common cases.

So my question here is far more, will it be implemented in the (near) future?
Afaik it could be workarounded with a JS implementation, which adds a "<me>" entry into the options html and the execution fetches <me> and replaces with the current login user.

**Comment by hanneshal** [comment]
Hi,

it is not planned as far as I can tell. If so, the change has to be made in Znuny and not in this add-on.
If you have the need for such a property, please open a feature request in the feature request repo for [Znuny](https://github.com/znuny/znuny-feature-requests) .

Without looking to much into the detail, the implementation has to be done in TicketSearch.pm, not in JS. 
The ticket search already has the current user as parameter. "Just" needs to be made aware of a new parameter which uses this user id for the owner. 
The main issue here is, that the profiles store fixed values, so we need to tell the ticket search to use a (to be created) parameter. 

regards
