### ISSUE TITLE
make Addon available for LTS version

### ISSUE THREAD

**Issue by SteffenMuehlnickel** [znuny/Znuny-DashboardWidgetSearchProfile#2]
Hi,
any chance this addon could be made available for LTS version 6.5.5? I'm unable to add it to my 6.5.5 installation, browsing the znuny repository to download it manually does not work either. Or offer the binary package via github?

Kind regards,

Steffen

**Comment by hanneshal** [comment]
Hi, 

this addon is temporarily pulled due to an issue where search profiles have been overwritten.

It will be back soon.

Regards

**Comment by SteffenMuehlnickel** [comment]
Hallo Johannes,

vielen Dank für die Rückmeldung. Kannst du abschätzen, wann das Addin wieder der Allgemeinheit zur Verfügung steht?
Ich habe bei mir eine handvoll Nutzer, die das Addin schmerzlich vermissen nach dem znuny Update.

Viele Grüße
Steffen Mühlnickel
IT


***@***.***


plano solutions gmbh
An der Schloßmauer 2c
98693 Ilmenau

***@***.***

+49 3677 689787220

www.interflex.com<https://www.interflex.com>
www.plano-wfm.com<https://www.plano-wfm.com>

plano solutions gmbh, An der Schloßmauer 2c, 98693 Ilmenau, Amtsgericht HRB 519639, USt.-Id-Nr.: DE355 089 147
Geschäftsführer: Robert Schüler, Bart Michiels, Bernhard Sommer
Bankverbindung: Deutsche Bank AG, IBAN DE26 8207 0000 0638 4366 00 | SWIFT DEUTDE8EXXX
Von: Johannes Nickel ***@***.***>
Gesendet: Dienstag, 30. Januar 2024 17:59
An: znuny/Znuny-DashboardWidgetSearchProfile ***@***.***>
Cc: Mühlnickel, Steffen ***@***.***>; Author ***@***.***>
Betreff: Re: [znuny/Znuny-DashboardWidgetSearchProfile] make Addon available for LTS version (Issue #2)

Hi, this addon is temporarly pulled due to an issue where search profiles have been overwritten. It will be back soon. Regards — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored


Hi,

this addon is temporarly pulled due to an issue where search profiles have been overwritten.

It will be back soon.

Regards

**Comment by rkaldung** [comment]
The add-on is available again via the open-source add-on repository.
